name: Feature Request
description: Suggest a new feature for AlgVex ATS
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Thank you for taking the time to suggest improvements!
        Please provide as much detail as possible.

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of feature is this?
      options:
        - New Trading Strategy
        - Model Enhancement (Qlib)
        - Data Source Integration
        - Risk Management
        - Performance Optimization
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "A clear and concise description of what the problem is. Ex: I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details (Optional)
      description: If you have ideas on how to implement this, please share
      placeholder: |
        - Files to modify:
        - Approach:
        - Dependencies:

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I am willing to submit a PR for this feature
