name: General Issue
description: Open a general issue
title: "[General]: "
labels: ["general"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to discuss?
    validations:
      required: true
